AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Teamwork Challenge Task Generators

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.11
    Architectures:
    - x86_64

Resources:
  TaskGeneratorsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: main.handler
      Events:
        WebApi:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          API_KEY_SECRET_NAME: teamwork-challenge-api-key
      Policies:
        - SecretsManagerReadWrite
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole

Outputs:
  TaskGeneratorsApi:
    Description: "API Gateway endpoint URL for Prod stage for Task Generators function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/docs"
  TaskGeneratorsFunction:
    Description: "Task Generators Lambda Function ARN"
    Value: !GetAtt TaskGeneratorsFunction.Arn
