name: mypy

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  type-check:
    name: Mypy type check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements-dev.txt
            back/requirements-dev.txt
            cli/requirements-dev.txt
            tasks/requirements-dev.txt

      - name: Install mypy
        run: pip install -r requirements-dev.txt

      # Optional but recommended if your mypy checks rely on local packages and type stubs
      - name: Install dev dependencies (back/cli/tasks)
        run: |
          pip install -r back/requirements-dev.txt
          pip install -r cli/requirements-dev.txt
          pip install -r tasks/requirements-dev.txt

      - name: Run mypy
        run: mypy --config-file mypy.ini back cli tasks