name: mypy

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  type-check:
    name: Mypy type check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install mypy
        run: pip install -r requirements.txt

      - name: Run mypy
        run: mypy --config-file mypy.ini back cli